program Trolledge;

uses
  System.StartUpCopy,
  FMX.Forms,
  uMain in 'uMain.pas' {frmMain},
  uMemoFrame in 'uMemoFrame.pas' {MemoFrame: TFrame},
  duck in 'duck.pas',
  uWorkFiles in 'uWorkFiles.pas',
  uFilesTree in 'uFilesTree.pas',
  uConsts in 'uConsts.pas',
  HS_FMXHints in 'HS_FMXHints.pas',
  uUtils in 'uUtils.pas',
  uPlugin in 'PluginsSystem\uPlugin.pas',
  uPluginEdit in 'PluginsSystem\uPluginEdit.pas' {fPluginEdit},
  OpenViewUrl in 'PluginsSystem\OpenViewUrl.pas',
  uPluginUtils in 'PluginsSystem\uPluginUtils.pas',
  FMX.Features.BitmapHelper in 'PluginsSystem\FMX.Features.BitmapHelper.pas',
  uMemoHexView in 'uMemoHexView.pas',
  uScripts in 'uScripts.pas',
  uZipView in 'uZipView.pas',
  CCR.Clipboard.FMX.Win in 'CCRClipboard\CCR.Clipboard.FMX.Win.pas',
  CCR.Clipboard.FMX in 'CCRClipboard\CCR.Clipboard.FMX.pas',
  CCR.Clipboard.Consts in 'CCRClipboard\CCR.Clipboard.Consts.pas',
  CCR.Clipboard in 'CCRClipboard\CCR.Clipboard.pas',
  CCR.Clipboard.Win in 'CCRClipboard\CCR.Clipboard.Win.pas',
  uFileTypeHelper in 'uFileTypeHelper.pas',
  uMemoBinaryView in 'uMemoBinaryView.pas',
  CCR.Clipboard.Apple in 'CCRClipboard\CCR.Clipboard.Apple.pas',
  CCR.Clipboard.Apple.Helpers in 'CCRClipboard\CCR.Clipboard.Apple.Helpers.pas',
  CCR.Clipboard.FMX.Mac in 'CCRClipboard\CCR.Clipboard.FMX.Mac.pas',
  uOptions in 'uOptions.pas' {OptionsFrame: TFrame},
  JsonDataObjects in 'Source\JsonDataObjects.pas',
  SvCollections.Tries in 'Source\SvCollections.Tries.pas',
  DelphiAST.Classes in 'Source\AST\DelphiAST.Classes.pas',
  DelphiAST.Consts in 'Source\AST\DelphiAST.Consts.pas',
  DelphiAST in 'Source\AST\DelphiAST.pas',
  DelphiAST.Writer in 'Source\AST\DelphiAST.Writer.pas',
  SimpleParser.Lexer in 'Source\AST\SimpleParser\SimpleParser.Lexer.pas',
  SimpleParser.Lexer.Types in 'Source\AST\SimpleParser\SimpleParser.Lexer.Types.pas',
  SimpleParser in 'Source\AST\SimpleParser\SimpleParser.pas',
  SimpleParser.Types in 'Source\AST\SimpleParser\SimpleParser.Types.pas',
  OBufferedStreams in 'Source\OXML\units\OBufferedStreams.pas',
  ODictionary in 'Source\OXML\units\ODictionary.pas',
  OEncoding in 'Source\OXML\units\OEncoding.pas',
  OHashedStrings in 'Source\OXML\units\OHashedStrings.pas',
  OJSON in 'Source\OXML\units\OJSON.pas',
  OTextReadWrite in 'Source\OXML\units\OTextReadWrite.pas',
  OWideSupp in 'Source\OXML\units\OWideSupp.pas',
  OXmlCDOM in 'Source\OXML\units\OXmlCDOM.pas',
  OXmlCSeq in 'Source\OXML\units\OXmlCSeq.pas',
  OXmlDOMVendor in 'Source\OXML\units\OXmlDOMVendor.pas',
  OXmlLng in 'Source\OXML\units\OXmlLng.pas',
  OXmlPDOM in 'Source\OXML\units\OXmlPDOM.pas',
  OXmlPSeq in 'Source\OXML\units\OXmlPSeq.pas',
  OXmlReadWrite in 'Source\OXML\units\OXmlReadWrite.pas',
  OXmlRTTISerialize in 'Source\OXML\units\OXmlRTTISerialize.pas',
  OXmlSAX in 'Source\OXML\units\OXmlSAX.pas',
  OXmlSerialize in 'Source\OXML\units\OXmlSerialize.pas',
  OXmlUtils in 'Source\OXML\units\OXmlUtils.pas',
  OXmlXPath in 'Source\OXML\units\OXmlXPath.pas',
  uTreeeUtils in 'uTreeeUtils.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
